name: Build Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: quay.io/sugarcrm/blackhole
          tag-sha: false # add git short SHA as Docker tag
          tag-semver: |
            v{{version}}
            v{{major}}.{{minor}}
            v{{major}}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: sergey_telpuk
          password: a9347892

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            KMINION_VERSION=sha-${{ github.sha }}
